### PR TITLE
feat(TextManipulation): Add HTML/XML stripping tags

### PR DESCRIPTION
**Pull request by mcolomer**
Hi @lublak,

Good job! You have a great node (very useful for non technical users).

I modified your community-node to strip HTML/XML tags.
This is useful when they want to get only text.

Let me know if this can be merged with the official package, or if you want to apply any modification.

Take care!

### CODE REVIEW

**Comment by lublak** [comment]
Hi @mcolomer,

thanks for your kind words :).
Thank you for your pull request.
I will want to think about it for now.
There is already an area called "Replace" with which it already works the way you do it.
Of course, it makes sense to store certain things that you need more often as options. I am thinking about whether it makes sense to store predefined regexes with a selection of regexes in replace. Html tags, new line, etc.

What would your opinion be on that?

**Comment by mcolomer** [comment]
I think the goal is to simplify the life to end users with usability. 

Most of them have no idea on regex expressions. Using a regex selector would be really useful for all of them (and for me too ;).

**Comment by lublak** [comment]
@mcolomer and which option would you prefer. An option in the regex selection or an extra entry?

**Comment by mcolomer** [comment]
I think it would be better to add an extra selector.

I mean, when you choose "Replace Mode: Regex" a new selector appears to choose between different predefined regexs:
- html tags
- numbers
- alpha
- ... (More options in the future)
- custom

Custom shows the current inputs.  
Do you think its more usable for end user?

**Comment by lublak** [comment]
@mcolomer It would be more general. Having predefined regexes instead of a strip function would be more practical. Perhaps there would then not be replace by "regex" but replace by "predefined rules".
The selector with the predefined rules would then be in there. Since not everything has to be a regex in the future.

- Replace
	- Substring
		- All
		- Extended
	- Extended Substring
		- All
		- Extended
	- Regex
		- Extended
	- Predefined Rules
		-  html tags
		- numbers
		- alpha
		- newline
		- ...

**Comment by mcolomer** [comment]
Yeah.

This makes sense to me. 
And it's easier to find it.

**Comment by lublak** [comment]
@mcolomer good :) then I will work on it next week. 👍

**Comment by mcolomer** [comment]
Perfect!

Let me know if you need a tester ;)

**Comment by lublak** [comment]
@mcolomer i moved everything to a new pull request

**Pull request merged**
